-- TODO: Тут лучше запихать сиквенс внутри таблицы, иначе при каждом запуске у тебя будет вылетать ошибка, что sequence already exists
CREATE TABLE IF NOT EXISTS products
(
    id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 3),
    name  VARCHAR(200) NOT NULL ,
    description VARCHAR(254) NOT NULL ,
    price BIGINT  NOT NULL
);